### ISSUE TITLE
Absolute URL is used twice

### ISSUE THREAD

**Issue by jgordijn** [arthepsy/sonar-scala-extra#4]
When I use the plugin, sonar cannot find the scala sources. The reason is that baseDir is concatenated with sourceDirectory and they are both absolute paths. It works fine, when I use the sonar-runner, but the error happens when I use maven sonar-runner or from sbt.

It can be fixed by putting the following if statement in in ScapegoatReportSensor.java line 175

``` java
File sourceDirectoryFile = new File(baseDir, sourceDirectory);
```

into

``` java
File sourceDirectoryFile;
if(sourceDirectory.startsWith(baseDirPath)) {
             sourceDirectoryFile = new File(sourceDirectory);
} else {
        sourceDirectoryFile = new File(baseDir, sourceDirectory);
 }
```

Can you please release a new version with this fix, or provide another solution to my problem.
Thanks!

**Comment by arthepsy** [comment]
Thanks for bugreport, @jgordijn. Please, verify that latest release fixes the issue.

**Comment by jgordijn** [comment]
O wow, that's awesome. Thanks for the fast response. I'm not able to test currently. I will test this on thursday and get back to you.

**Comment by jgordijn** [comment]
The issue is fixed.
